### ISSUE TITLE
自定义相机拍摄图片的时候，图片结果旋转

### ISSUE THREAD

**Issue by LCBbest** [zhanglinfeng/LFKit#2]
自定义相机拍摄图片的时候，图片结果旋转，竖着拍的图片，显示到imgview中旋转90度或180度，使用网上和项目自带的方法【fixOrientation】也没有效果。麻烦看一下

**Comment by iCodey** [comment]
哥们我也遇到这个问题，fixOrientation也没用，你解决了吗

**Comment by LCBbest** [comment]
> 哥们我也遇到这个问题，fixOrientation也没用，你解决了吗

解决了 ，不怎呢看邮件，你现在还需要吗？如果需要加我qq 970500147
