### ISSUE TITLE
气泡绘制

### ISSUE THREAD

**Issue by Winstonokk** [zhanglinfeng/LFKit#3]
在底部右下方的按钮 上方显示这个气泡，显示不全，只显示了左边内容，如何设置三角在气泡底部右侧

**Comment by zhanglinfeng** [comment]
有截图看看么？你使用的代码也发出来看看

**Comment by Winstonokk** [comment]
按钮在右下方靠边，代码如下：
 NSString *strTip = @"可设置边框线，三角大小，三角位置，圆角大小，背景色";
    LFBubbleView *bubbleView  = [[LFBubbleView alloc] initWithFrame:CGRectMake(0, 0, 200, 160)];
    bubbleView.direction = LFTriangleDirection_Down;//三角方向
    bubbleView.lbTitle.text = strTip;//文字
    bubbleView.borderColor = [UIColor grayColor];//边框颜色
    bubbleView.borderWidth = 1;//边框线宽
    bubbleView.triangleH = 20;//三角高
    bubbleView.triangleW = 20;//三角底边长
    bubbleView.triangleXY = 40;//三角中心的x
    bubbleView.cornerRadius = 20;//气泡圆角
    bubbleView.color = [UIColor orangeColor];//气泡颜色
    [self.view addSubview:bubbleView];
    [bubbleView showInPoint:CGPointMake(self.openBtn.center.x, self.openBtn.center.y - 20)];

效果图：
![2023_06_30_09_09_IMG_0491](https://github.com/zhanglinfeng/LFKit/assets/16253450/17ab0222-39a1-46f3-97b0-10877c847672)

**Comment by zhanglinfeng** [comment]
你这个场景bubbleView.triangleXY指的是三角的中心距气泡左边的距离，你设置40太小了，换成160试试
